/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotingIndexRouteImport } from './routes/voting/index'
import { Route as VotingEthIndexRouteImport } from './routes/voting-eth/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AshleyIndexRouteImport } from './routes/ashley/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEthIndexRouteImport } from './routes/admin-eth/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotingIndexRoute = VotingIndexRouteImport.update({
  id: '/voting/',
  path: '/voting/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotingEthIndexRoute = VotingEthIndexRouteImport.update({
  id: '/voting-eth/',
  path: '/voting-eth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AshleyIndexRoute = AshleyIndexRouteImport.update({
  id: '/ashley/',
  path: '/ashley/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEthIndexRoute = AdminEthIndexRouteImport.update({
  id: '/admin-eth/',
  path: '/admin-eth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-eth/': typeof AdminEthIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/ashley/': typeof AshleyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/voting-eth/': typeof VotingEthIndexRoute
  '/voting/': typeof VotingIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-eth': typeof AdminEthIndexRoute
  '/admin': typeof AdminIndexRoute
  '/ashley': typeof AshleyIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/voting-eth': typeof VotingEthIndexRoute
  '/voting': typeof VotingIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-eth/': typeof AdminEthIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/ashley/': typeof AshleyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/voting-eth/': typeof VotingEthIndexRoute
  '/voting/': typeof VotingIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-eth/'
    | '/admin/'
    | '/ashley/'
    | '/dashboard/'
    | '/voting-eth/'
    | '/voting/'
    | '/auth/signin/'
    | '/auth/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-eth'
    | '/admin'
    | '/ashley'
    | '/dashboard'
    | '/voting-eth'
    | '/voting'
    | '/auth/signin'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/admin-eth/'
    | '/admin/'
    | '/ashley/'
    | '/dashboard/'
    | '/voting-eth/'
    | '/voting/'
    | '/auth/signin/'
    | '/auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEthIndexRoute: typeof AdminEthIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AshleyIndexRoute: typeof AshleyIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  VotingEthIndexRoute: typeof VotingEthIndexRoute
  VotingIndexRoute: typeof VotingIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voting/': {
      id: '/voting/'
      path: '/voting'
      fullPath: '/voting/'
      preLoaderRoute: typeof VotingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voting-eth/': {
      id: '/voting-eth/'
      path: '/voting-eth'
      fullPath: '/voting-eth/'
      preLoaderRoute: typeof VotingEthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ashley/': {
      id: '/ashley/'
      path: '/ashley'
      fullPath: '/ashley/'
      preLoaderRoute: typeof AshleyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-eth/': {
      id: '/admin-eth/'
      path: '/admin-eth'
      fullPath: '/admin-eth/'
      preLoaderRoute: typeof AdminEthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEthIndexRoute: AdminEthIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AshleyIndexRoute: AshleyIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  VotingEthIndexRoute: VotingEthIndexRoute,
  VotingIndexRoute: VotingIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
